== `guarded`

The `guarded` functions allow an `async_operation`
while holding the synchronization primitive (i.e. a <<semaphore>> or <<mutex>>) automatically.

.semaphore
****
Function to run OPs only when the <<semaphore>> can be acquired.
That way an artificial number of processes can run in parallel.

*Type Parameters*

*  `Executor`        The executor of the semaphore.
*  `CompletionToken` The completion token

*Parameters*

*  `sm` The semaphore to guard the protection
*  `op` The operation to guard.
*  `completion_token` The completion token to use for the async completion.

[source,cpp]
----
template<typename Executor, typename Op,
         net::completion_token_for<net::completion_signature_of_t<Op>> CompletionToken>
auto guarded(basic_semaphore<Executor> & sm, Op && op,
             CompletionToken && token = net::default_token<Executor>);
----
****

.mutex
****
Function to run OPs only when the <<mutex>> can be locked.
Unlocks the mutex on completion.

*Type Parameters*

*  `Executor`        The executor of the semaphore.
*  `CompletionToken` The completion token

*Parameters*

*  `mtx` The mutex to guard the protection
*  `op`  The operation to guard.
*  `completion_token` The completion token to use for the async completion.

[source,cpp]
----
template<typename Executor, typename Op,
         net::completion_token_for<net::completion_signature_of_t<Op>> CompletionToken>
auto guarded(basic_mutex<Executor> & mtx, Op && op,
             CompletionToken && token = net::default_token<Executor>);
----
****